app_name: dfood
env: production
port: 80
db:
  driver: sqlite3
  datasource: prod.db
log_level: warn
sendgrid:
  api_key: ${SENDGRID_API_KEY}
  from_email: abubakarissa47722@gmail.com
  from_name: dfood
jwt:
  secret: ${JWT_SECRET}
