app_name: dfood
env: dev
port: 8080
db:
  driver: sqlite3
  datasource: dev.db
log_level: debug
sendgrid:
  api_key: ${SENDGRID_API_KEY}
  from_email: abubakarissa47722@gmail.com
  from_name: dfood Development
