app_name: dfood
env: staging
port: 8081
db:
  driver: sqlite3
  datasource: staging.db
log_level: info
sendgrid:
  api_key: ${SENDGRID_API_KEY}
  from_email: abubakarissa47722@gmail.com
  from_name: dfood Staging
