package main

import (
	"dfood/internal/config"
	"dfood/internal/service"
	"fmt"
	"log"
)

// Example of how to use the email service
func main() {
	// Load config
	cfg, err := config.New()
	if err != nil {
		log.Fatal("Failed to load config:", err)
	}

	// Initialize email service
	emailService := service.NewEmailService(service.EmailConfig{
		APIKey:    cfg.SendGrid.APIKey,
		FromEmail: cfg.SendGrid.FromEmail,
		FromName:  cfg.SendGrid.FromName,
	})

	// Example 1: Send welcome email
	welcomeSubject := "Welcome to dfood!"
	welcomePlainText := `Hi John Doe,

Welcome to dfood! We're excited to have you join our community of food lovers.

You can now:
- Discover amazing restaurants
- Share your dining experiences through reviews
- Help others find great places to eat

Start exploring and sharing your food journey with us!

Best regards,
The dfood Team`

	welcomeHTML := `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Welcome to dfood</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #2c3e50;">Welcome to dfood!</h1>
        <p>Hi John Doe,</p>
        <p>Welcome to dfood! We're excited to have you join our community of food lovers.</p>
        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0;">
            <h3 style="margin-top: 0;">You can now:</h3>
            <ul>
                <li>Discover amazing restaurants</li>
                <li>Share your dining experiences through reviews</li>
                <li>Help others find great places to eat</li>
            </ul>
        </div>
        <p>Start exploring and sharing your food journey with us!</p>
        <p>Best regards,<br>The dfood Team</p>
    </div>
</body>
</html>`

	err = emailService.SendEmail("user@example.com", "John Doe", welcomeSubject, welcomePlainText, welcomeHTML)
	if err != nil {
		fmt.Printf("Failed to send welcome email: %v\n", err)
	} else {
		fmt.Println("Welcome email sent successfully!")
	}

	// Example 2: Send password reset email
	resetToken := "abc123xyz789" // This would be generated by your auth system
	resetURL := fmt.Sprintf("https://dfood.com/reset-password?token=%s", resetToken)

	resetSubject := "Reset Your dfood Password"
	resetPlainText := fmt.Sprintf(`Hi John Doe,

We received a request to reset your dfood password.

Click the link below to reset your password:
%s

This link will expire in 1 hour for security reasons.

If you didn't request this password reset, please ignore this email. Your password will remain unchanged.

Best regards,
The dfood Team`, resetURL)

	resetHTML := fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Reset Your dfood Password</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #2c3e50;">Reset Your Password</h1>
        <p>Hi John Doe,</p>
        <p>We received a request to reset your dfood password.</p>
        <div style="text-align: center; margin: 30px 0;">
            <a href="%s" style="background-color: #3498db; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block;">Reset Password</a>
        </div>
        <p><strong>This link will expire in 1 hour</strong> for security reasons.</p>
        <p>If you didn't request this password reset, please ignore this email. Your password will remain unchanged.</p>
        <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
        <p style="font-size: 12px; color: #666;">
            If the button doesn't work, copy and paste this link into your browser:<br>
            %s
        </p>
        <p>Best regards,<br>The dfood Team</p>
    </div>
</body>
</html>`, resetURL, resetURL)

	err = emailService.SendEmail("user@example.com", "John Doe", resetSubject, resetPlainText, resetHTML)
	if err != nil {
		fmt.Printf("Failed to send password reset email: %v\n", err)
	} else {
		fmt.Println("Password reset email sent successfully!")
	}

	// Example 3: Send generic custom email
	subject := "Special Offer from dfood!"
	plainText := "Hi John, we have a special 20% discount for you at your favorite restaurants!"
	htmlContent := `
	<h2>Special Offer!</h2>
	<p>Hi John,</p>
	<p>We have a <strong>20% discount</strong> for you at your favorite restaurants!</p>
	<p>Use code: <code>SAVE20</code></p>
	`

	err = emailService.SendEmail("user@example.com", "John Doe", subject, plainText, htmlContent)
	if err != nil {
		fmt.Printf("Failed to send custom email: %v\n", err)
	} else {
		fmt.Println("Custom email sent successfully!")
	}
}
